# This workflow has 2 roles:
# - Create the release PR.
# - Create the release tag and artifact (once the release PR is merged).
name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Print release-please outputs
        env:
          RELEASE_PLEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: |
          echo "${RELEASE_PLEASE_OUTPUTS}" | jq
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp -a cli/asdf-plugin-manager.sh asdf-plugin-manager-${{ steps.release.outputs.tag_name }}.sh
          gh release upload ${{ steps.release.outputs.tag_name }} asdf-plugin-manager-${{ steps.release.outputs.tag_name }}.sh
